// Modifica le frasi dalla pagina admin.html.
window.MARTINA_FEEDBACK = {
  "positive": [
    "Esatto. Ti concedo un cenno di approvazione molto teatrale.",
    "Risposta giusta: il nostro gruppo WhatsApp può stare tranquillo.",
    "Ci hai preso. Quasi sospetto che tu abbia studiato.",
    "Brava. Hai evitato una piccola crisi diplomatica con me.",
    "Perfetto. Hai appena guadagnato punti anche nella vita reale.",
    "Confermo: almeno uno dei miei vocali l’hai ascoltato davvero.",
    "Esattamente. Mi sento vista, capita e leggermente spiata.",
    "Giusta. Ti sei meritata il posto accanto a me all’aperitivo.",
    "Molto bene. Inizio a considerarti una minaccia per le altre.",
    "Centro pieno. La nostra amicizia ha basi sorprendentemente solide.",
    "Corretto. Prendo diligentemente nota per il titolo di migliore amica.",
    "Lo sapevi. Adesso puoi anche vantartene, ma con moderazione.",
    "Risposta impeccabile. Annuisco dall’alto della mia importanza.",
    "Sì. Evidentemente nei momenti cruciali mi prestavi attenzione.",
    "Esatto. Il nostro archivio di inside joke non è stato costruito invano.",
    "Bravissima. Questa vale almeno mezzo spritz offerto da me.",
    "Hai indovinato. Approvo senza riserve, evento piuttosto raro.",
    "Perfetta. A questo ritmo potrei affidarti persino le mie password.",
    "Giustissima. Sei pericolosamente vicina allo status di anima gemella.",
    "Bingo. Mi conosci decisamente troppo bene e la cosa mi preoccupa.",
    "Esatto. Per questa domanda non segnalo traumi relazionali.",
    "Corretto. Certifico personalmente la tua preparazione nel gossip.",
    "Che classe. Risposta giusta e dignità della nostra amicizia preservata.",
    "Proprio così. Probabilmente te lo racconto da almeno tre anni.",
    "Ottimo colpo. Le altre possono iniziare a prendere appunti.",
    "Sì, sì e ancora sì. Questa era roba da vere intenditrici di me.",
    "Risposta esatta. Puoi continuare a definirti una persona informata.",
    "Ti concedo applausi discreti ma convinti: hai capito tutto.",
    "Perfetto. La nostra amicizia supera un altro controllo qualità.",
    "Ci sei arrivata. Sono orgogliosa, anche se non lo ammetterò mai più."
  ],
  "negative": [
    "No. Sto rivalutando tutta la nostra amicizia.",
    "Sbagliato. Ci serve urgentemente un aperitivo chiarificatore.",
    "Ahi. Questa me la ricorderò sicuramente nel gruppo.",
    "Nope. Sono delusa, ma per ora andiamo avanti.",
    "Errore grave. Ho già iniziato a registrarti un vocale.",
    "Non proprio. Forse quei sette minuti di mio audio andavano ascoltati.",
    "Risposta sbagliata. Pretendo spiegazioni ufficiali.",
    "Male. Molto male. Fingiamo che fosse una mia domanda trabocchetto.",
    "No. Il nostro prossimo caffè avrà un’atmosfera particolare.",
    "Questa fa male. Pensavo fossimo più vicine.",
    "Hai mancato il bersaglio con una sicurezza quasi ammirevole.",
    "Sbagliata. Ho appena trattenuto il respiro per la delusione.",
    "No. Durante i nostri aperitivi eri evidentemente distratta.",
    "Ahi. Sto rivalutando il tuo posto al tavolo delle migliori amiche.",
    "Niente da fare. Mi aspettavo decisamente di più da te.",
    "Risposta errata. Apro immediatamente un’indagine interna.",
    "Non ci siamo. Però ammiro la convinzione con cui hai cliccato.",
    "No. La nostra amicizia ha bisogno di un aggiornamento software.",
    "Brutta caduta. Tranquilla: ne parlerò soltanto per sempre.",
    "Sbagliato. Sto già cercando le ricevute delle nostre conversazioni.",
    "Questa non era difficile. Almeno secondo me, che faccio le regole.",
    "Errore registrato: lo userò nelle future discussioni passive-aggressive.",
    "Nope. Un’altra così e ti iscrivo al corso di recupero su di me.",
    "Ahi ahi. La tua memoria selettiva oggi non ti sta aiutando.",
    "No. Potrei chiederti di restituire il titolo di bestie.",
    "Sbagliata. Ti salva soltanto il fatto che nessuno è perfetto.",
    "Questa risposta mi ha appena dato materiale per tre nuovi meme.",
    "Non esattamente. Ne riparliamo davanti a un drink.",
    "Errore. Sorrido, ma dentro sto prendendo appunti.",
    "No. Per fortuna non ho ancora previsto l’espulsione dal gruppo."
  ]
};
