// Modifica le frasi dalla pagina admin.html.
window.MARTINA_FEEDBACK = {
  "positive": [
    "Esatto. Martina approverebbe con un cenno molto teatrale.",
    "Risposta giusta: il vostro gruppo WhatsApp può stare tranquillo.",
    "Ci hai preso. Quasi sospetto che tu abbia studiato.",
    "Brava. Hai evitato una piccola crisi diplomatica.",
    "Perfetto. Hai appena guadagnato punti anche nella vita reale.",
    "Confermo: almeno una dei suoi vocali l’hai ascoltata davvero.",
    "Esattamente. Martina si sente vista, capita e leggermente spiata.",
    "Giusta. Ti sei ufficialmente meritata il posto accanto a lei all’aperitivo.",
    "Molto bene. Le altre iniziano a percepirti come una minaccia.",
    "Centro pieno. Questa amicizia ha basi sorprendentemente solide.",
    "Corretto. La commissione migliore amica prende diligentemente nota.",
    "Lo sapevi. E adesso puoi anche vantartene con moderazione.",
    "Risposta impeccabile. Martina annuisce dall’alto della sua importanza.",
    "Sì. Evidentemente nei momenti cruciali prestavi attenzione.",
    "Esatto. Il vostro archivio di inside joke non è stato costruito invano.",
    "Bravissima. Questa vale almeno mezzo spritz offerto.",
    "Hai indovinato. La chat delle amiche approva senza riserve.",
    "Perfetta. A questo ritmo Martina ti affida anche le password.",
    "Giustissima. Sei pericolosamente vicina allo status di anima gemella.",
    "Bingo. Qualcuna qui conosce decisamente troppo bene la situazione.",
    "Esatto. Nessun trauma relazionale da segnalare per questa domanda.",
    "Corretto. Il reparto gossip certifica la tua preparazione.",
    "Che classe. Risposta giusta e dignità dell’amicizia preservata.",
    "Proprio così. Martina probabilmente lo racconta da almeno tre anni.",
    "Ottimo colpo. Le concorrenti sono invitate a prendere appunti.",
    "Sì, sì e ancora sì. Questa era roba da vere intenditrici.",
    "Risposta esatta. Puoi continuare a definirti una persona informata.",
    "Applausi discreti ma convinti: hai capito tutto.",
    "Perfetto. La vostra amicizia supera un altro controllo qualità.",
    "Ci sei arrivata. Martina è orgogliosa, anche se non lo ammetterà."
  ],
  "negative": [
    "No. Martina sta rivalutando tutta la vostra amicizia.",
    "Sbagliato. Serve urgentemente un aperitivo chiarificatore.",
    "Ahi. Questa verrà sicuramente ricordata nel gruppo.",
    "Nope. La delusione è palpabile, ma andiamo avanti.",
    "Errore grave. Martina ha già iniziato a scrivere un vocale.",
    "Non proprio. Forse quei sette minuti di audio andavano ascoltati.",
    "Risposta sbagliata. Il comitato amicizia chiede spiegazioni.",
    "Male. Molto male. Ma fingiamo che fosse una domanda trabocchetto.",
    "No. Il vostro prossimo caffè avrà un’atmosfera particolare.",
    "Questa fa male. Soprattutto a Martina, che pensava foste più vicine.",
    "Hai mancato il bersaglio con una sicurezza quasi ammirevole.",
    "Sbagliata. La chat di gruppo ha appena trattenuto il respiro.",
    "No. Qualcuna durante gli aperitivi era evidentemente distratta.",
    "Ahi. Il posto al tavolo delle migliori amiche ora traballa.",
    "Niente da fare. Martina si aspettava decisamente di più da te.",
    "Risposta errata. Parte immediatamente un’indagine interna.",
    "Non ci siamo. Però la convinzione con cui hai cliccato era notevole.",
    "No. Questa amicizia ha bisogno di un piccolo aggiornamento software.",
    "Brutta caduta. Tranquilla: le altre ne parleranno solo per sempre.",
    "Sbagliato. Martina sta cercando ricevute delle vostre conversazioni.",
    "Questa non era difficile. O almeno, così sosterrà Martina.",
    "Errore registrato e archiviato per future discussioni passive-aggressive.",
    "Nope. Un’altra così e scatta il corso di recupero.",
    "Ahi ahi. La memoria selettiva oggi non gioca a tuo favore.",
    "No. Martina potrebbe chiederti di restituire il titolo di bestie.",
    "Sbagliata. Ti salva soltanto il fatto che nessuno è perfetto.",
    "Questa risposta ha appena creato materiale per tre nuovi meme.",
    "Non esattamente. Mettiamola tra le cose da chiarire davanti a un drink.",
    "Errore. Martina sorride, ma dentro sta prendendo appunti.",
    "No. Per fortuna il test non prevede l’espulsione dal gruppo."
  ]
};
