// Modifica liberamente domande, risposte e commenti.
// correct indica la posizione della risposta corretta: 0 = prima, 1 = seconda, ecc.
window.MARTINA_QUESTIONS = [
  {category:"GUSTI & OSSESSIONI",question:"Qual è la colazione ideale di Martina?",answers:["Cappuccino e cornetto","Pancake e sciroppo d’acero","Solo caffè, grazie","Avocado toast"],correct:0},
  {category:"GUSTI & OSSESSIONI",question:"Quale stagione rappresenta meglio Martina?",answers:["Primavera","Estate","Autunno","Inverno"],correct:1},
  {category:"VITA QUOTIDIANA",question:"Quante sveglie imposta prima di alzarsi?",answers:["Una, disciplinatissima","Due, per sicurezza","Almeno cinque","Nessuna: si sveglia da sola"],correct:2},
  {category:"CIBO, OVVIAMENTE",question:"Quale pizza ordinerebbe senza pensarci?",answers:["Margherita","Diavola","Quattro formaggi","Bufala e crudo"],correct:3},
  {category:"VITA QUOTIDIANA",question:"Cosa dimentica più spesso quando esce?",answers:["Le chiavi","Il telefono","Il portafoglio","Gli occhiali da sole"],correct:0},
  {category:"VIAGGI & SOGNI",question:"Quale città sceglierebbe per un weekend improvvisato?",answers:["Parigi","Barcellona","Londra","Copenaghen"],correct:1},
  {category:"GUSTI & OSSESSIONI",question:"Qual è il suo colore preferito?",answers:["Verde salvia","Blu notte","Rosa cipria","Bordeaux"],correct:2},
  {category:"VITA QUOTIDIANA",question:"Quanto ritardo fa di solito?",answers:["Mai: arriva prima","Cinque minuti","Dieci minuti accademici","Il tempo è un concetto relativo"],correct:3},
  {category:"CIBO, OVVIAMENTE",question:"Qual è il suo comfort food definitivo?",answers:["Pasta al pomodoro","Sushi","Patatine fritte","Gelato"],correct:0},
  {category:"AMICIZIE & DRAMA",question:"Come reagisce Martina davanti a un gossip succoso?",answers:["Cambia discorso","Chiede tutti i dettagli","Fa finta di niente","Manda subito un vocale"],correct:1},
  {category:"MUSICA & SERIE",question:"Cosa guarda quando vuole staccare il cervello?",answers:["Un documentario","Un thriller complicatissimo","Una commedia romantica","Un tutorial di cucina"],correct:2},
  {category:"CIBO, OVVIAMENTE",question:"Che gusto di gelato sceglierebbe?",answers:["Limone e fragola","Pistacchio e nocciola","Cioccolato fondente","Stracciatella e crema"],correct:3},
  {category:"VITA QUOTIDIANA",question:"Qual è la prima app che apre al mattino?",answers:["WhatsApp","Instagram","TikTok","Meteo"],correct:0},
  {category:"VIAGGI & SOGNI",question:"Quale sarebbe la sua vacanza perfetta?",answers:["Trekking in montagna","Mare, lettino e aperitivo","Tour tra musei","Campeggio senza segnale"],correct:1},
  {category:"AMICIZIE & DRAMA",question:"Qual è la frase che Martina dice più spesso?",answers:["Ragazze, tranquilli","Non ho niente da mettere","Giuro, sto arrivando","Ne parliamo dopo"],correct:2},
  {category:"GUSTI & OSSESSIONI",question:"Quale superpotere sceglierebbe?",answers:["Invisibilità","Leggere nel pensiero","Volare","Teletrasportarsi"],correct:3},
  {category:"CIBO, OVVIAMENTE",question:"Cosa ordina all’aperitivo?",answers:["Spritz","Gin tonic","Vino bianco","Analcolico alla frutta"],correct:0},
  {category:"MUSICA & SERIE",question:"Che tipo di playlist mette per prepararsi?",answers:["Indie malinconico","Pop da cantare a squarciagola","Jazz rilassante","Silenzio assoluto"],correct:1},
  {category:"VITA QUOTIDIANA",question:"Quanto è ordinata la sua borsa?",answers:["Tutto diviso per categorie","Accettabile, dai","Un universo inesplorato","Non porta mai la borsa"],correct:2},
  {category:"AMICIZIE & DRAMA",question:"Cosa fa se un’amica le scrive ‘ti devo raccontare una cosa’?",answers:["Risponde il giorno dopo","Manda un punto interrogativo","Fa uno screenshot","Chiama immediatamente"],correct:3},
  {category:"GUSTI & OSSESSIONI",question:"Quale animale la rappresenta di più?",answers:["Gatto","Cane","Volpe","Delfino"],correct:0},
  {category:"VIAGGI & SOGNI",question:"Quale mezzo sceglierebbe per un viaggio lungo?",answers:["Auto, con playlist infinita","Aereo, per arrivare subito","Treno, guardando fuori","Nave, con calma"],correct:1},
  {category:"CIBO, OVVIAMENTE",question:"Quale dolce la convince sempre?",answers:["Cheesecake","Cannolo","Tiramisù","Crostata"],correct:2},
  {category:"VITA QUOTIDIANA",question:"Quante foto scatta prima di sceglierne una?",answers:["Una basta e avanza","Tre o quattro","Una decina","Meglio non contarle"],correct:3},
  {category:"AMICIZIE & DRAMA",question:"Qual è il suo ruolo nel gruppo di amiche?",answers:["L’organizzatrice","La terapeuta","Quella che arriva tardi","La responsabile dei meme"],correct:0},
  {category:"MUSICA & SERIE",question:"Come guarda una serie che le piace?",answers:["Un episodio a settimana","Tutta in una notte","Solo in compagnia","Legge prima gli spoiler"],correct:1},
  {category:"GUSTI & OSSESSIONI",question:"Quale regalo la renderebbe più felice?",answers:["Un libro","Un gioiello","Un viaggio a sorpresa","Un elettrodomestico"],correct:2},
  {category:"VITA QUOTIDIANA",question:"Qual è il suo rapporto con i vocali?",answers:["Li detesta","Solo sotto i trenta secondi","Preferisce scrivere","Podcast da sette minuti"],correct:3},
  {category:"VIAGGI & SOGNI",question:"Dove si siederebbe in aereo?",answers:["Finestrino","Corridoio","In mezzo, senza problemi","Vicino all’uscita"],correct:0},
  {category:"LA DOMANDA FINALE",question:"Quanto pensa di essere simpatica Martina?",answers:["Abbastanza, dai","Iconica, ovviamente","Dipende dalla giornata","Non ha opinioni in merito"],correct:1}
];
